# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: F-dev Preview CICD

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
on:
  push:
    branches: [ "F-dev" ]
  pull_request:
    branches: [ "F-dev" ]

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Install Vercel CLI
          run : npm install --global vercel

        - name: Pull Vercel Env Info
          run : vercel pull --yes --environment=Preview --token=${{ secrets.VERCEL_TOKEN}}

        - name: Build Project Artifacts
          run : vercel build --token=${{ secrets.VERCEL_TOKEN}}

        - name: Deploy Project Artifacts
          run : vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN}} 
        
  #       - name: Setup node.js 18.x
  #         uses: actions/setup-node@v3
  #         with:
  #           node-version: ${{ matrix.node-version }}
  #           cache: 'npm'
  #       - run: npm ci
  #       - run: npm run build --if-present
  #       - run: npm test

  # deploy:
  #     needs: build
  #     runs-on: F-dev
      
  #     steps:
  #       - name: install dependencies
  #         run: npm i --production

  #       - name: start app
  #         run: node app.js
